client:
	g++ main.cpp interface.cpp connection.cpp crypto.cpp -o main -lboost_program_options -lcryptopp
test:
	g++ UnitTest.cpp interface.cpp connection.cpp crypto.cpp -o UnitTest -lUnitTest++ -lboost_program_options -lcryptopp
	
